# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Cristian Vitorin
title: Lic. Negocios Internacionales
email: 200300033@ucaribe.edu.mx
website: https://vitorinlogistics.rocks/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: cristian vitorin
# flickr_username: jekyll
instagram_username: vitorin66
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title:"Acerca de mí"
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola mi nombre es cristian Rangel tengo 20 años, soy estudiante de la licenciatura en negocios internacionales. 

  Lo que más disfruto es viajar, trabajar y conocer nuevos países. 

content:
  - title: TRAYECTORIA ACADÉMICA# Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Instituciones educativas que me han formado academicamente.
        link: https://www.unicaribe.mx/
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          Escuela secundaria. Año 2014-2017. "Pilar Victoria Y Victoria" Peto Yucatán.
          Escuela media Superior. Año 2017-2020. "Colegio de Bachilleres del Estado de Yucatán" Peto Yuactán.
          Desde el año 2020 comecé mis estudios en la universidad del caribe, ubicado en la ciudad de cancun Quintana Roo. 
          Actualmente me encuentro cursando el cuarto semestre en la licenciarura en negocios internacionales.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fiesta inn Cancún Las Americas.
        link:  https://www.fiestainn.com/
        # link_text: https://www.fiestainn.com/
        sub_title: Asistente de Administracion
        caption: Diciembre 2021
        quote: >
          Fiesta inn es una empresa dedicada al sector hotelero, cada año hospeda a mas de 100,000 huespedes.
        description: | # this will include new lines to allow paragraphs
            La empresa me capacitó para tener conocimiento en la administracion de una empresa del sector hotelero.
            Tengo experiencia realizando Balances, libros contables, presupuesto anual, entre muchas otras cosas.
            Tengo una capacitacion en Administracion y contabilidad. Acreditada  por la secretaria de educacion publica.
            Desde a muy temprana edad comencé con proyectos emprendedores por lo que me considero una persona capacitada para desemvolverme y realizar negociaciones.
           
            

  - title: EDUCACIÓN # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left
        title: UNIVERSIDAD DEL CARIBE
        caption: 2020- PRESENTE
        sub_title: Lic. Negocios Internacionales.
        quote: >
          Alma mater.
 
        description: | # this will include new lines to allow paragraphs
          Actualmente me encuentro cursando el cuaro semestre en la licenciatura de negocios internacionales.

          Esta universidad ofrece grandes herramientas para formar alumnos altamente capacitados para que pueden desempeñar sus funciones en cualquier sector del turismo y de los negocios.
          

  - title: UN POCO MÁS SOBRE MI
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Lector apacionado
      - Conocimientos en edición y marketing
      - Amigable
      - Amante de los viajes

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
